### ISSUE TITLE
Favicon is missing

### ISSUE THREAD

**Issue by bilalmirza74** [mrvivacious/My_Bhagavad_Gita#27]
![image](https://github.com/mrvivacious/My_Bhagavad_Gita/assets/84387676/b59a6ca6-4b8a-4168-bc58-7e0f8331feb7)

i can add a favicon to this web application

**Comment by mrvivacious** [comment]
oh! good idea!

some icons i found that i think would be cool (im open to seeing what you were thinking too):
[Book outline](https://www.flaticon.com/free-icon/bhagavad-gita_3100802). I think it says Bhagavad Gita on the cover, i cant read the language!

[Om](https://www.alamy.com/om-symbol-black-image362132915.html). Doesn't have to be this specific one, just any om. I think a white logo would be preferred so that the favicon would appear clearly in the browser tab.
